// VeloSearch gRPC API.
//
// Service surface:
//   - Collection lifecycle:  CreateCollection / DropCollection / ListCollections
//   - Mutations:              Insert / Delete
//   - Queries:                Search / Stats
//
// Collections are multi-tenant: each has its own HNSW index, dimension,
// and distance metric. All RPCs are unary; streaming is out of scope for
// v0.1.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/velosearch.proto

package velosearchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metric selects the distance function used by the collection's index.
// Set at CreateCollection and immutable thereafter.
type Metric int32

const (
	Metric_METRIC_UNSPECIFIED Metric = 0
	Metric_METRIC_L2          Metric = 1
	Metric_METRIC_COSINE      Metric = 2
)

// Enum value maps for Metric.
var (
	Metric_name = map[int32]string{
		0: "METRIC_UNSPECIFIED",
		1: "METRIC_L2",
		2: "METRIC_COSINE",
	}
	Metric_value = map[string]int32{
		"METRIC_UNSPECIFIED": 0,
		"METRIC_L2":          1,
		"METRIC_COSINE":      2,
	}
)

func (x Metric) Enum() *Metric {
	p := new(Metric)
	*p = x
	return p
}

func (x Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_velosearch_proto_enumTypes[0].Descriptor()
}

func (Metric) Type() protoreflect.EnumType {
	return &file_proto_velosearch_proto_enumTypes[0]
}

func (x Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric.Descriptor instead.
func (Metric) EnumDescriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{0}
}

// Vector carries a single dense float32 vector.
type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_proto_velosearch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateCollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dim            int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	Metric         Metric                 `protobuf:"varint,3,opt,name=metric,proto3,enum=velosearch.v1.Metric" json:"metric,omitempty"`
	M              int32                  `protobuf:"varint,4,opt,name=m,proto3" json:"m,omitempty"`                                                 // HNSW M, typical 16
	EfConstruction int32                  `protobuf:"varint,5,opt,name=ef_construction,json=efConstruction,proto3" json:"ef_construction,omitempty"` // HNSW efConstruction, typical 200
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_METRIC_UNSPECIFIED
}

func (x *CreateCollectionRequest) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *CreateCollectionRequest) GetEfConstruction() int32 {
	if x != nil {
		return x.EfConstruction
	}
	return 0
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCollectionResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type DropCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{3}
}

func (x *DropCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dropped       bool                   `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionResponse) Reset() {
	*x = DropCollectionResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionResponse) ProtoMessage() {}

func (x *DropCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionResponse.ProtoReflect.Descriptor instead.
func (*DropCollectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{4}
}

func (x *DropCollectionResponse) GetDropped() bool {
	if x != nil {
		return x.Dropped
	}
	return false
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{5}
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{6}
}

func (x *ListCollectionsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_velosearch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{7}
}

func (x *Item) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{8}
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      int32                  `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{9}
}

func (x *InsertResponse) GetInserted() int32 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Ids           []uint32               `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         *Vector                `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`                               // number of neighbors to return
	EfSearch      int32                  `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"` // HNSW candidate set size at query time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetQuery() *Vector {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

type Hit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_proto_velosearch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{13}
}

func (x *Hit) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hit) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*Hit                 `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_velosearch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{15}
}

func (x *StatsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumVectors    int32                  `protobuf:"varint,1,opt,name=num_vectors,json=numVectors,proto3" json:"num_vectors,omitempty"`
	NumDeleted    int32                  `protobuf:"varint,2,opt,name=num_deleted,json=numDeleted,proto3" json:"num_deleted,omitempty"`
	NumLayers     int32                  `protobuf:"varint,3,opt,name=num_layers,json=numLayers,proto3" json:"num_layers,omitempty"`
	MemBytes      int64                  `protobuf:"varint,4,opt,name=mem_bytes,json=memBytes,proto3" json:"mem_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_velosearch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_velosearch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_velosearch_proto_rawDescGZIP(), []int{16}
}

func (x *StatsResponse) GetNumVectors() int32 {
	if x != nil {
		return x.NumVectors
	}
	return 0
}

func (x *StatsResponse) GetNumDeleted() int32 {
	if x != nil {
		return x.NumDeleted
	}
	return 0
}

func (x *StatsResponse) GetNumLayers() int32 {
	if x != nil {
		return x.NumLayers
	}
	return 0
}

func (x *StatsResponse) GetMemBytes() int64 {
	if x != nil {
		return x.MemBytes
	}
	return 0
}

var File_proto_velosearch_proto protoreflect.FileDescriptor

const file_proto_velosearch_proto_rawDesc = "" +
	"\n" +
	"\x16proto/velosearch.proto\x12\rvelosearch.v1\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xa5\x01\n" +
	"\x17CreateCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\x12-\n" +
	"\x06metric\x18\x03 \x01(\x0e2\x15.velosearch.v1.MetricR\x06metric\x12\f\n" +
	"\x01m\x18\x04 \x01(\x05R\x01m\x12'\n" +
	"\x0fef_construction\x18\x05 \x01(\x05R\x0eefConstruction\"4\n" +
	"\x18CreateCollectionResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\"+\n" +
	"\x15DropCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x16DropCollectionResponse\x12\x18\n" +
	"\adropped\x18\x01 \x01(\bR\adropped\"\x18\n" +
	"\x16ListCollectionsRequest\"/\n" +
	"\x17ListCollectionsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"E\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12-\n" +
	"\x06vector\x18\x02 \x01(\v2\x15.velosearch.v1.VectorR\x06vector\"Z\n" +
	"\rInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.velosearch.v1.ItemR\x05items\",\n" +
	"\x0eInsertResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x05R\binserted\"A\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\rR\x03ids\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted\"\x87\x01\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12+\n" +
	"\x05query\x18\x02 \x01(\v2\x15.velosearch.v1.VectorR\x05query\x12\f\n" +
	"\x01k\x18\x03 \x01(\x05R\x01k\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\x05R\befSearch\"1\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"8\n" +
	"\x0eSearchResponse\x12&\n" +
	"\x04hits\x18\x01 \x03(\v2\x12.velosearch.v1.HitR\x04hits\".\n" +
	"\fStatsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"\x8d\x01\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\vnum_vectors\x18\x01 \x01(\x05R\n" +
	"numVectors\x12\x1f\n" +
	"\vnum_deleted\x18\x02 \x01(\x05R\n" +
	"numDeleted\x12\x1d\n" +
	"\n" +
	"num_layers\x18\x03 \x01(\x05R\tnumLayers\x12\x1b\n" +
	"\tmem_bytes\x18\x04 \x01(\x03R\bmemBytes*B\n" +
	"\x06Metric\x12\x16\n" +
	"\x12METRIC_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMETRIC_L2\x10\x01\x12\x11\n" +
	"\rMETRIC_COSINE\x10\x022\xcd\x04\n" +
	"\fVectorSearch\x12c\n" +
	"\x10CreateCollection\x12&.velosearch.v1.CreateCollectionRequest\x1a'.velosearch.v1.CreateCollectionResponse\x12]\n" +
	"\x0eDropCollection\x12$.velosearch.v1.DropCollectionRequest\x1a%.velosearch.v1.DropCollectionResponse\x12`\n" +
	"\x0fListCollections\x12%.velosearch.v1.ListCollectionsRequest\x1a&.velosearch.v1.ListCollectionsResponse\x12E\n" +
	"\x06Insert\x12\x1c.velosearch.v1.InsertRequest\x1a\x1d.velosearch.v1.InsertResponse\x12E\n" +
	"\x06Delete\x12\x1c.velosearch.v1.DeleteRequest\x1a\x1d.velosearch.v1.DeleteResponse\x12E\n" +
	"\x06Search\x12\x1c.velosearch.v1.SearchRequest\x1a\x1d.velosearch.v1.SearchResponse\x12B\n" +
	"\x05Stats\x12\x1b.velosearch.v1.StatsRequest\x1a\x1c.velosearch.v1.StatsResponseB9Z7github.com/zhangchuqi1998/velosearch/proto;velosearchv1b\x06proto3"

var (
	file_proto_velosearch_proto_rawDescOnce sync.Once
	file_proto_velosearch_proto_rawDescData []byte
)

func file_proto_velosearch_proto_rawDescGZIP() []byte {
	file_proto_velosearch_proto_rawDescOnce.Do(func() {
		file_proto_velosearch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_velosearch_proto_rawDesc), len(file_proto_velosearch_proto_rawDesc)))
	})
	return file_proto_velosearch_proto_rawDescData
}

var file_proto_velosearch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_velosearch_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_velosearch_proto_goTypes = []any{
	(Metric)(0),                      // 0: velosearch.v1.Metric
	(*Vector)(nil),                   // 1: velosearch.v1.Vector
	(*CreateCollectionRequest)(nil),  // 2: velosearch.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil), // 3: velosearch.v1.CreateCollectionResponse
	(*DropCollectionRequest)(nil),    // 4: velosearch.v1.DropCollectionRequest
	(*DropCollectionResponse)(nil),   // 5: velosearch.v1.DropCollectionResponse
	(*ListCollectionsRequest)(nil),   // 6: velosearch.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),  // 7: velosearch.v1.ListCollectionsResponse
	(*Item)(nil),                     // 8: velosearch.v1.Item
	(*InsertRequest)(nil),            // 9: velosearch.v1.InsertRequest
	(*InsertResponse)(nil),           // 10: velosearch.v1.InsertResponse
	(*DeleteRequest)(nil),            // 11: velosearch.v1.DeleteRequest
	(*DeleteResponse)(nil),           // 12: velosearch.v1.DeleteResponse
	(*SearchRequest)(nil),            // 13: velosearch.v1.SearchRequest
	(*Hit)(nil),                      // 14: velosearch.v1.Hit
	(*SearchResponse)(nil),           // 15: velosearch.v1.SearchResponse
	(*StatsRequest)(nil),             // 16: velosearch.v1.StatsRequest
	(*StatsResponse)(nil),            // 17: velosearch.v1.StatsResponse
}
var file_proto_velosearch_proto_depIdxs = []int32{
	0,  // 0: velosearch.v1.CreateCollectionRequest.metric:type_name -> velosearch.v1.Metric
	1,  // 1: velosearch.v1.Item.vector:type_name -> velosearch.v1.Vector
	8,  // 2: velosearch.v1.InsertRequest.items:type_name -> velosearch.v1.Item
	1,  // 3: velosearch.v1.SearchRequest.query:type_name -> velosearch.v1.Vector
	14, // 4: velosearch.v1.SearchResponse.hits:type_name -> velosearch.v1.Hit
	2,  // 5: velosearch.v1.VectorSearch.CreateCollection:input_type -> velosearch.v1.CreateCollectionRequest
	4,  // 6: velosearch.v1.VectorSearch.DropCollection:input_type -> velosearch.v1.DropCollectionRequest
	6,  // 7: velosearch.v1.VectorSearch.ListCollections:input_type -> velosearch.v1.ListCollectionsRequest
	9,  // 8: velosearch.v1.VectorSearch.Insert:input_type -> velosearch.v1.InsertRequest
	11, // 9: velosearch.v1.VectorSearch.Delete:input_type -> velosearch.v1.DeleteRequest
	13, // 10: velosearch.v1.VectorSearch.Search:input_type -> velosearch.v1.SearchRequest
	16, // 11: velosearch.v1.VectorSearch.Stats:input_type -> velosearch.v1.StatsRequest
	3,  // 12: velosearch.v1.VectorSearch.CreateCollection:output_type -> velosearch.v1.CreateCollectionResponse
	5,  // 13: velosearch.v1.VectorSearch.DropCollection:output_type -> velosearch.v1.DropCollectionResponse
	7,  // 14: velosearch.v1.VectorSearch.ListCollections:output_type -> velosearch.v1.ListCollectionsResponse
	10, // 15: velosearch.v1.VectorSearch.Insert:output_type -> velosearch.v1.InsertResponse
	12, // 16: velosearch.v1.VectorSearch.Delete:output_type -> velosearch.v1.DeleteResponse
	15, // 17: velosearch.v1.VectorSearch.Search:output_type -> velosearch.v1.SearchResponse
	17, // 18: velosearch.v1.VectorSearch.Stats:output_type -> velosearch.v1.StatsResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_velosearch_proto_init() }
func file_proto_velosearch_proto_init() {
	if File_proto_velosearch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_velosearch_proto_rawDesc), len(file_proto_velosearch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_velosearch_proto_goTypes,
		DependencyIndexes: file_proto_velosearch_proto_depIdxs,
		EnumInfos:         file_proto_velosearch_proto_enumTypes,
		MessageInfos:      file_proto_velosearch_proto_msgTypes,
	}.Build()
	File_proto_velosearch_proto = out.File
	file_proto_velosearch_proto_goTypes = nil
	file_proto_velosearch_proto_depIdxs = nil
}
